"""Prepare a full-stack local test from a test_config.yaml (driven by test-local.bat).

Reads S3 and LLM settings plus the config-a2a / web-a2a paths, generates the
shared RS256 keys and distributes them to the three repos, writes a derived
mcp-fs config (config/test-local.yaml) pointed at the given S3 endpoint, and
emits a batch fragment (state/test-local.vars.bat) of ``set`` statements that
test-local.bat consumes. Cross-platform; meant to be run through the batch file.

Usage:  uv run python scripts/test_local_prepare.py <test_config.yaml>
"""

from __future__ import annotations

import shutil
import sys
import time
from pathlib import Path
from urllib.parse import urlparse

import jwt
import yaml
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

FS_ROOT = Path(__file__).resolve().parent.parent


def _die(message: str) -> None:
    sys.exit(f"test_local_prepare: {message}")


def _require(mapping: dict, key: str, section: str) -> str:
    value = mapping.get(key)
    if not value:
        _die(f"{section}.{key} is required in the test config")
    return str(value)


def _write_keys(repo: Path, files: dict[str, bytes]) -> None:
    (repo / ".keys").mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (repo / ".keys" / name).write_bytes(data)


def _mcp_config(endpoint: str, access_key: str, secret_key: str, admin: str) -> str:
    return f"""# Generated by scripts/test_local_prepare.py - do not edit by hand.
server:
  host: "0.0.0.0"
  port: 8080
  mcp_path: "/mcp"
auth:
  admins: ["{admin}"]
  jwt:
    public_key_path: ".keys/jwt.pub"
    header: "X-Forwarded-Authorization"
    algorithms: ["RS256"]
    audience: null
    issuer: "web-a2a"
    username_claim: "email"
infra:
  meta:
    backend: "sqlite"
    dir: "state/volumes"
  blob:
    backend: "s3"
    endpoint: "{endpoint}"
    access_key: "{access_key}"
    secret_key: "{secret_key}"
    bucket_prefix: "mcpfs-"
    region: "us-east-1"
  admin:
    backend: "sqlite"
    path: "state/admin.db"
safety:
  write_quota_bytes: 52428800
  trash_dir: ".mcp_trash"
  read_guard: true
  allow_hard_delete: false
  max_read_lines: 2000
"""


def main() -> None:
    cfg_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("test_config.yaml")
    if not cfg_path.is_file():
        _die(f"config not found: {cfg_path}")
    cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8")) or {}

    s3 = cfg.get("s3", {})
    llm = cfg.get("llm", {})
    paths = cfg.get("paths", {})

    endpoint = _require(s3, "endpoint", "s3")
    access_key = str(s3.get("access_key", "testing"))
    secret_key = str(s3.get("secret_key", "testing"))
    start_moto = bool(s3.get("start_moto", True))

    llm_base = _require(llm, "base_url", "llm")
    llm_key = _require(llm, "api_key", "llm")
    llm_model = str(llm.get("model", "openrouter/auto"))

    config_a2a = Path(_require(paths, "config_a2a", "paths"))
    web_a2a = Path(_require(paths, "web_a2a", "paths"))
    if not config_a2a.is_dir():
        _die(f"paths.config_a2a not found: {config_a2a}")
    if not web_a2a.is_dir():
        _die(f"paths.web_a2a not found: {web_a2a}")

    admin = str(cfg.get("admin_email", "seb.morand@gmail.com"))
    mount = str(cfg.get("mount_id", "perso-seb"))

    # Shared RS256 keys plus a discovery service token, distributed to the three repos.
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_pem = key.private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()
    )
    public_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    now = int(time.time())
    service = jwt.encode(
        {"email": "service@web-a2a", "iss": "web-a2a", "iat": now, "exp": now + 315360000},
        private_pem,
        algorithm="RS256",
    ).encode("utf-8")
    _write_keys(FS_ROOT, {"jwt.key": private_pem, "jwt.pub": public_pem, "service.jwt": service})
    _write_keys(config_a2a, {"jwt.pub": public_pem, "service.jwt": service})
    _write_keys(web_a2a, {"jwt.key": private_pem, "jwt.pub": public_pem})

    (FS_ROOT / "config" / "test-local.yaml").write_text(
        _mcp_config(endpoint, access_key, secret_key, admin), encoding="utf-8"
    )

    parsed_port = urlparse(endpoint).port
    moto_port = str(parsed_port) if parsed_port else "5000"
    enc_key = Fernet.generate_key().decode("ascii")

    state = FS_ROOT / "state"
    state.mkdir(exist_ok=True)

    # Ensure the launched shells find uv even without a login shell / rc file: prepend
    # its directory to PATH in every run-* script (belt and suspenders next to
    # kitty's --copy-env, which also carries PATH and the LLM env vars).
    uv_bin = shutil.which("uv")
    uv_dir = str(Path(uv_bin).parent) if uv_bin else ""

    def _bat(name: str, lines: list[str]) -> None:
        head = [f'set "PATH={uv_dir};%PATH%"'] if uv_dir and name.startswith("run-") else []
        (state / name).write_text("\r\n".join(["@echo off", *head, *lines]) + "\r\n", encoding="utf-8")

    # Per-service launch scripts (values baked in, so test-local.bat needs no nested quotes).
    _bat("run-moto.bat", [f'cd /d "{FS_ROOT}"', f"uv run moto_server -p {moto_port}"])
    _bat("run-mcp-fs.bat", [f'cd /d "{FS_ROOT}"', "uv run mcp-fs serve --config config\\test-local.yaml"])
    _bat(
        "run-config-a2a.bat",
        [
            f'cd /d "{config_a2a}"',
            f'set "OPENROUTER_API_KEY={llm_key}"',
            'set "MCP_FS_URL=http://127.0.0.1:8080/mcp"',
            f'set "MCP_FS_MOUNT={mount}"',
            f'set "LLM_MODEL={llm_model}"',
            f'set "LLM_BASE_URL={llm_base}"',
            "uv run agent --config config_examples\\mcp-fs-moto\\agents.template.yaml",
        ],
    )
    _bat(
        "run-web-a2a.bat",
        [
            f'cd /d "{web_a2a}"',
            'set "AGENT_CHAT_DATABASE_URL=sqlite+aiosqlite:///./state/web-a2a.db"',
            f'set "AGENT_CHAT_ENCRYPTION_KEY={enc_key}"',
            'set "AGENT_CHAT_SECRET_KEY=change-me-local"',
            f'set "AGENT_CHAT_A2A_JWT_SIGNING_KEY_PATH={web_a2a / ".keys" / "jwt.key"}"',
            "if not exist state mkdir state",
            "uv run alembic upgrade head",
            "uv run uvicorn agent_chat.app:app --host 0.0.0.0 --port 8000",
        ],
    )
    # Variables the orchestrator itself needs (moto toggle, provisioning identity).
    _bat(
        "test-local.vars.bat",
        [
            f'set "START_MOTO={"1" if start_moto else "0"}"',
            f'set "MCP_FS_MOUNT={mount}"',
            f'set "ADMIN_EMAIL={admin}"',
        ],
    )

    def _sh(name: str, lines: list[str]) -> None:
        head = [f'export PATH="{uv_dir}:$PATH"'] if uv_dir and name.startswith("run-") else []
        (state / name).write_text("#!/usr/bin/env bash\n" + "\n".join([*head, *lines]) + "\n", encoding="utf-8")

    # Same launch commands for macOS / Linux (used by test-local.sh via kitty tabs).
    _sh("run-moto.sh", [f'cd "{FS_ROOT}"', f"exec uv run moto_server -p {moto_port}"])
    _sh("run-mcp-fs.sh", [f'cd "{FS_ROOT}"', "exec uv run mcp-fs serve --config config/test-local.yaml"])
    _sh(
        "run-config-a2a.sh",
        [
            f'cd "{config_a2a}"',
            f'export OPENROUTER_API_KEY="{llm_key}"',
            'export MCP_FS_URL="http://127.0.0.1:8080/mcp"',
            f'export MCP_FS_MOUNT="{mount}"',
            f'export LLM_MODEL="{llm_model}"',
            f'export LLM_BASE_URL="{llm_base}"',
            "exec uv run agent --config config_examples/mcp-fs-moto/agents.template.yaml",
        ],
    )
    _sh(
        "run-web-a2a.sh",
        [
            f'cd "{web_a2a}"',
            'export AGENT_CHAT_DATABASE_URL="sqlite+aiosqlite:///./state/web-a2a.db"',
            f'export AGENT_CHAT_ENCRYPTION_KEY="{enc_key}"',
            'export AGENT_CHAT_SECRET_KEY="change-me-local"',
            f'export AGENT_CHAT_A2A_JWT_SIGNING_KEY_PATH="{web_a2a / ".keys" / "jwt.key"}"',
            "mkdir -p state",
            "uv run alembic upgrade head",
            "exec uv run uvicorn agent_chat.app:app --host 0.0.0.0 --port 8000",
        ],
    )
    _sh(
        "test-local.vars.sh",
        [
            f'export START_MOTO="{"1" if start_moto else "0"}"',
            f'export MCP_FS_MOUNT="{mount}"',
            f'export ADMIN_EMAIL="{admin}"',
        ],
    )

    print("prepared:")
    print(f"  keys distributed to mcp-fs, {config_a2a}, {web_a2a}")
    print("  wrote config/test-local.yaml")
    print("  wrote state/run-*.bat and run-*.sh (per-service launch scripts)")
    print(f"  start moto: {start_moto} (port {moto_port})")


if __name__ == "__main__":
    main()
